[package]
name = "hajsori_xyz"
version = "0.1.0"
edition = "2024"

[dependencies]
rshtml = "0.2.0"
actix-web = "4.0"
actix-files = "0.6.6"

[package.metadata.rshtml]
views = { path = "src/pages", layout = "layout.rs.html" }
